export const defectsName = [
    "Broken stitch",
    "Needle mark",
    " Open seam",
    "Fabric fault",
    "Drop stitch",
    "Needle hole",
    "Improper tuck",
    "Improper shape",
    "Joint stitch",
    "Label fault",
    " Measurement",
    "Oil spot",
    "Dirty spot",
    "Puckering",
    "Pleat",
    "Wrong SPI",
    "Yarn oont",
    "Rawedge",
    "Reverse",
    "Slanted",
    "Skip stitch",
    "Shading",
    "Thread mistake",
    "Twisting",
    "Thread tension",
    "Up down",
    "Un even",
    "Uncut thread",
    "Wavyness",
    "Pocket",
    "Side band",
    // <input type="text" />,
    // <input type="text" />,
    // <input type="text" />,
    // <input type="text" />,
    // <input type="text" />,
    // <input type="text" />,
    ".",
    "Rejects",
    // <input type="text" />,
    "*",
    "Total check gmts",
    "Total Pass gmts",
    "Total defective gmts",
    "Total defects qty",
    "DHU%",
    "Defective rectified qty",
    "Defective balance qty",
    "Rectify Defective check &",
    "Rejects qty",
    "Supervisor signature",
  ];
  
  export const cuttingDefectsName = [
    "Name",
    "Style",
    "Order No",
    "Ins Qty",
    "Ok Qty",
    "Defect Qnty",
    "Defects %",
    "Narrow Goods",
    "Laying Defected",
    "Hole",
    "Dia Variation",
    "Crese Mark",
    "Pin Hole",
    "Needle Mark",
    "Yarn Contramination",
    "Patta",
    "Dirty Spot",
    "Oil spot",
    "Mix shade",
    "Lycra Out",
    "Slub",
    "Halriness",
    "Naps",
    "shinkar Mark",
    "Loop",
    "Lycra Out",
    "Missing Yarn",
    "Softner Spot ",
    "Compacting Mark",
    "Stralpe Y/D",
    "Running Shade",
    "Spot/Dust",
    "Bowling",
    "Other Fault",
  ];
  
  export const defectsTime = [ '08-09', '09-10', '10-11', '11-12', '12-01','02-03', '03-04', '04-05', '05-06', '06-07', 'Total' ]